# Learn Numpy


In [9]:
import numpy as np

In [212]:
a = [1, 2, 3, 4 ,5]
print(a)
print(a[1])
print(a[1:4])
print(a[-1])


[1, 2, 3, 4, 5]
2
[2, 3, 4]
5


In [18]:
a = np.array([1,2,3, 4, 5,6])
print(a)
print(type(a))
print(a[1])
print(a[1:])
print(a[:-2])
      

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
2
[2 3 4 5 6]
[1 2 3 4]


In [22]:
a[2] = 10
print(a)

[ 1  2 10  4  5  6]


In [250]:
import numpy as np

a_1d = np.array([1, 2, 3])  # 1D array
a_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 2D array
am = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 11, 12]])  # 2D array
a_3d = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]
])  # 3D array
al = np.array([
    [[1, 2], [3, 4]],
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])  # 3D array

print("a_1d.ndim : ", a_1d.ndim)  # Output: 1
print("a_2d.ndim : ",a_2d.ndim)  # Output: 2
print("ar.ndim : ",ar.ndim)
print("am.ndim : ",am.ndim)
print("a_3d : ", a_3d.ndim)  # Output: 3
print("al : ", al.ndim)

a_1d.ndim :  1
a_2d.ndim :  2
ar.ndim :  2
am.ndim :  2
a_3d :  3
al :  3


In [11]:
a_mul = np.array([
    [1, 2, 3],
    [4, 5 ,6],
    [7, 8, 9]
])
print(a_mul[0])
print(a_mul[0, 1])

[1 2 3]
2


In [13]:
print(a_mul.shape)

(3, 3)


In [15]:
print(a_mul.ndim)

2


In [17]:
print(a_mul.size)

9


In [19]:
print(a_mul.dtype)

int32


In [254]:
a = np.array([
    [1, 2, 3],
    [4, "hello" ,6],
    [7, 8, 9]
])

print(a.dtype)
print(type(a[0][0]))

<U11
<class 'numpy.str_'>


In [29]:
a = np.array([
    [1, 2, 3],
    [4, "5" ,6],
    [7, 8, 9]], dtype=np.int32
)
print(a.dtype)
print(a[0][0].dtype)


int32
int32


In [33]:
a = np.array([
    [1, 2, 3],
    [4, "5" ,6],
    [7, 8, 9]], dtype=np.float32
)

print(a.dtype)
print(a[1][1].dtype)
print(a[1,1])

float32
float32
5.0


In [37]:
a = np.full((2, 3, 4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [39]:
a = np.zeros((3, 4, 5))
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [41]:
a = np.ones((2, 3, 4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [45]:
a = np.empty((3, 3, 3))
print(a)

[[[6.23042070e-307 4.67296746e-307 1.08521774e-311]
  [1.08521774e-311 1.08522462e-311 1.08521774e-311]
  [1.08521774e-311 1.08521774e-311 1.08521774e-311]]

 [[1.08521774e-311 1.08521774e-311 1.08521774e-311]
  [1.08521774e-311 1.08522462e-311 1.08521774e-311]
  [1.08520567e-311 1.08522462e-311 1.08521774e-311]]

 [[1.08522292e-311 1.08521774e-311 1.08521774e-311]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 3.91792476e-317]]]


In [256]:
x_values = np.arange(0, 1000, 5)
print(x_values)

print("---------------------------------------")

x_values = np.linspace(0, 1000, 2)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]
---------------------------------------
[   0. 1000.]


In [51]:
print(np.nan)
print(np.inf)

nan
inf


In [53]:
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


In [258]:
arr = np.array([1.0, np.nan, 3.5, np.nan, 5.2])
result = np.isnan(arr)
print(result) 

[False  True False  True False]


In [57]:
print(np.sqrt(-1))
print(np.array([10]) / 0)

nan
[inf]


C:\Users\amira\AppData\Local\Temp\ipykernel_12400\2389277247.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\amira\AppData\Local\Temp\ipykernel_12400\2389277247.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10]) / 0)


In [262]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5)
print(a1 * 5)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [69]:
print(a1 * 5)
print(l1 + 5)

[ 5 10 15 20 25]


TypeError: can only concatenate list (not "int") to list

In [75]:
print(l1 + l2)
print(a1 + a2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 7  9 11 13  5]


In [79]:
print(a1 / a2)
print(l1 / l2)


[0.16666667 0.28571429 0.375      0.44444444        inf]


C:\Users\amira\AppData\Local\Temp\ipykernel_12400\4154995301.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a1 / a2)


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [81]:
print(a1 - a2)
print(l1 - l2)

[-5 -5 -5 -5  5]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [85]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1],
              [2]])

print(a1 * a2)

[[1 2 3]
 [2 4 6]]


In [89]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 1], [2,1]])

print(a1 + a2)

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [91]:
a = np.array([[1, 2, 3], [4, 5,6 ]])
print(np.log10(a))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


In [110]:
a = np.array([1, 2, 3])
print(np.append(a, [7, 8, 9]))
print(a)
a = np.insert(a, 1, [10, 11, 12])
print(a)

[1 2 3 7 8 9]
[1 2 3]
[ 1 10 11 12  2  3]


In [114]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
print(np.delete(a, 1))
print(np.delete(a, 3))
print(np.delete(a, 4))

[1 3 4 5 6]
[1 2 3 5 6]
[1 2 3 4 6]


In [116]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
print(np.delete(a, 1, 0))
print("----------------------------------------------")
print(np.delete(a, 0, 0))
print("----------------------------------------------")
print(np.delete(a, 1, 1))

[[1 2 3]]
----------------------------------------------
[[4 5 6]]
----------------------------------------------
[[1 3]
 [4 6]]


In [131]:
print(a.shape)
print("--------------------------------------------")
print(a.reshape((3,2)))


(2, 3)
--------------------------------------------
[[1 2]
 [3 4]
 [5 6]]


In [133]:
a = np.array([[1, 2, 3 , 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])
print(a.shape)
print("-------------------------------------")
print(a.reshape((5, 4)))
print("-------------------------------------")
print(a.reshape((20,)))
print("-------------------------------------")
print(a.reshape((20, 1)))
print("-------------------------------------")
print(a.reshape((2, 10)))
print("-------------------------------------")
print(a.reshape((2, 2, 5)))
print("-------------------------------------")
print(a.reshape((2, 5, 2)))
print("-------------------------------------")
print(a.reshape((2, 10)))

(4, 5)
-------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
-------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
-------------------------------------
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
-------------------------------------
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
-------------------------------------
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
-------------------------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
-------------------------------------
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [135]:
print(a.resize(10, 2))
print(a)

None
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [137]:
print(a.flatten())
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [141]:
var1 = a.flatten()
var1[2] = 100
print(var1)
print("-----------------------------")
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
-----------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [143]:
var1 = a.ravel()
var1[2] = 100
print(var1)
print("-----------------------------")
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
-----------------------------
[[  1   2]
 [100   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]]


In [266]:
var = [v for v in a.flat]
print(var)

['1', '2', '3', '4', 'hello', '6', '7', '8', '9']


In [154]:
a = np.array([[1, 2, 3 , 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])


print(a.transpose())
print("---------------------")
print(a.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
---------------------
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [156]:
print(a.swapaxes(0, 1))

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [160]:
a1 = np.array([[1, 2, 3, 4, 5], 
               [6, 7, 8 , 9, 10]])

a2 = np.array([[11, 12, 13, 14, 15], 
               [16, 17, 18, 19, 20]])

a = np.concatenate((a1, a2), axis=0)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [162]:
a = np.concatenate((a1, a2), axis=1)
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [168]:
a = np.stack((a1, a2))
print(a)
print("------------------------------")
a = np.hstack((a1, a2))
print(a)
print("--------------------------------")
a = np.vstack((a1, a2))
print(a)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
------------------------------
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
--------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [270]:
a = np.array([[1, 2, 3 , 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(np.split(a, 2, axis=0))
print("-------------------------------------------------------")
print(np.split(a, 4, axis=0))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
-------------------------------------------------------
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


In [180]:
a = np.array([[1, 2, 3 , 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print("a.min : ", a.min())
print("a.max : ", a.max())
print("a.mean : ", a.mean())
print("a.std : ", a.std())
print("a.sum : ", a.sum())
print("a.median : ", np.median(a))

a.min :  1
a.max :  20
a.mean :  10.5
a.std :  5.766281297335398
a.sum :  210
a.median :  10.5


In [186]:
number = np.random.randint(100)
print(number)

97


In [192]:
numbers = np.random.randint(100, size=(2, 3, 4))
print(numbers)

[[[72 53 74  1]
  [36 30 45 72]
  [29 57 30 18]]

 [[19 72  9 74]
  [ 0 53 28 62]
  [39  2 92 97]]]


In [198]:
numbers = np.random.normal(loc=170, scale=15, size=(5,10))
print(numbers)

[[176.73945555 149.33561892 167.60663899 150.35827558 191.79395735
  181.25029298 192.3906186  190.79284974 165.92167841 161.6785052 ]
 [166.34100642 181.04774909 204.49151918 180.88886031 192.97070589
  177.47966688 171.37852922 160.16772868 178.02213864 169.0457449 ]
 [176.71168163 163.63996853 165.13964747 166.27698738 184.09430485
  154.06614868 177.04158614 181.83746605 171.82308908 178.09680514]
 [174.69267277 168.73702385 196.79785665 155.97881045 197.69532805
  174.6796758  173.24666243 146.9573939  168.90841166 133.04433734]
 [191.69470247 175.60677832 191.57172729 175.6430228  158.11584006
  182.49468096 160.39764142 154.83890464 161.66493387 172.3347758 ]]


In [200]:
numbers = np.random.choice([10, 20, 30, 40, 50], size=(5, 10))
print(numbers)

[[30 40 10 20 50 30 50 50 40 40]
 [20 50 50 10 40 10 50 10 10 40]
 [20 10 30 20 10 50 20 40 40 10]
 [30 20 30 10 10 30 20 30 40 50]
 [50 30 50 50 30 50 30 40 10 20]]


In [206]:
a = np.array([[1, 2, 3 , 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

# np.save("array.npy", a)
a = np.load("array.npy")
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [210]:
# np.savetxt("myarray.csv", a, delimiter=",")
a = np.loadtxt("myarray.csv", delimiter=",")
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
